---
apiVersion: v1
kind: Pod
metadata:
  name: zookeepeer-client
  namespace: default
spec:
  containers:
  - name: zookeepeer-client
    image: gcr.io/google-containers/kubernetes-zookeeper:1.0-3.4.10
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always


---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-client
  namespace: default
spec:
  containers:
  - name: kafka-client
    # image: gcr.io/google-containers/kubernetes-kafka:1.0-10.2.0
    image: docker.io/wurstmeister/kafka:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: kafka-certificates
      mountPath: /opt/bitnami/kafka/conf/certs/
      readOnly: true
   
  volumes:
    - name: kafka-certificates
      secret:
        secretName: kafka-secret
        defaultMode: 25
  restartPolicy: Always 


---
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: default
spec:
  containers:
  - name: dnsutils
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always

